# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

# CodeRabbit Configuration for DISC Leader
# AI-powered code review configuration optimized for TypeScript/React/TanStack/Convex

language: en-US
early_access: true
enable_free_tier: true

reviews:
  # Review profile: "chill" for balanced feedback, "assertive" for stricter reviews
  profile: chill
  
  # Request changes workflow
  request_changes_workflow: false
  
  # High-level summary settings
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  
  # Review status and commit status
  review_status: true
  commit_status: true
  fail_commit_status: false
  
  # Additional review features
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  
  # Path filters - exclude generated files and dependencies
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!**/package-lock.json"
    - "!**/bun.lock"
    - "!**/convex/_generated/**"
    - "!**/routeTree.gen.ts"
  
  # Path-specific review instructions
  path_instructions:
    - path: "src/**/*.{ts,tsx}"
      instructions: |
        - Review TypeScript/React code for best practices
        - Ensure proper typing with TypeScript (avoid 'any' types)
        - Check for proper React Hook usage and dependencies
        - Verify TanStack Router patterns are followed correctly
        - Ensure components are properly exported and typed
        - Check for accessibility concerns with React Aria Components
        - Verify proper error handling
        
    - path: "convex/**/*.ts"
      instructions: |
        - Review Convex query/mutation patterns
        - Ensure proper schema definitions with validators
        - Check for proper indexing on tables
        - Verify authentication/authorization is properly implemented
        - Ensure mutations have proper validation
        
    - path: "src/routes/**/*.tsx"
      instructions: |
        - Review TanStack Router route definitions
        - Ensure proper loader/component patterns
        - Check for proper error boundaries
        - Verify proper data fetching patterns
        
    - path: "**/*.test.{ts,tsx}"
      instructions: |
        - Review test coverage and quality
        - Ensure tests are well-organized and descriptive
        - Check for proper mocking with MSW if needed
        - Verify Vitest best practices
  
  # Abort review when PR is closed
  abort_on_close: true
  disable_cache: false
  
  # Auto review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - WIP
      - draft
      - DO NOT REVIEW
    labels: []
    drafts: false
    base_branches:
      - main
      - develop
  
  # Finishing touches - automatic improvements
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: false  # Set to true if you want AI to suggest unit tests
  
  # Integrated tools configuration
  tools:
    # TypeScript/JavaScript linters
    eslint:
      enabled: true
    
    # Biome (fast linter/formatter)
    biome:
      enabled: true
    
    # Oxlint (Rust-based fast linter)
    oxc:
      enabled: true
    
    # Markdown linting
    markdownlint:
      enabled: true
    
    # GitHub Actions linting
    actionlint:
      enabled: true
    
    # Shell script checking
    shellcheck:
      enabled: true
    
    # YAML linting
    yamllint:
      enabled: true
    
    # Security scanning
    gitleaks:
      enabled: true
    
    # Dockerfile linting
    hadolint:
      enabled: true
    
    # HTML linting
    htmlhint:
      enabled: true
    
    # Environment file linting
    dotenvLint:
      enabled: true
    
    # GitHub checks integration
    github-checks:
      enabled: true
      timeout_ms: 90000
    
    # Disable tools not relevant to this project
    ruff:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    golangci-lint:
      enabled: false
    flake8:
      enabled: false
    rubocop:
      enabled: false
    pmd:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    cppcheck:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    pylint:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false

# Chat configuration
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto

# Knowledge base configuration
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/**/*.md"
      - "*.md"
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto

# Code generation settings
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "src/**/*.{ts,tsx}"
        instructions: |
          - Use JSDoc format for TypeScript/React components
          - Include @param, @returns, and @example when relevant
          - Keep docstrings concise but informative
          
      - path: "convex/**/*.ts"
        instructions: |
          - Use JSDoc format for Convex functions
          - Document query/mutation parameters and return types
          - Include usage examples for complex functions
  
  unit_tests:
    path_instructions:
      - path: "src/**/*.{ts,tsx}"
        instructions: |
          - Use Vitest for unit tests
          - Follow the Arrange-Act-Assert pattern
          - Use descriptive test names that explain the behavior being tested
          - Mock external dependencies appropriately

