/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminScorekeeperGameIdRouteImport } from './routes/admin.scorekeeper.$gameId'
import { Route as AdminGamesNewRouteImport } from './routes/admin.games.new'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScorekeeperGameIdRoute = AdminScorekeeperGameIdRouteImport.update({
  id: '/scorekeeper/$gameId',
  path: '/scorekeeper/$gameId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin/'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin/'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GamesGameIdRoute: typeof GamesGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scorekeeper/$gameId': {
      id: '/admin/scorekeeper/$gameId'
      path: '/scorekeeper/$gameId'
      fullPath: '/admin/scorekeeper/$gameId'
      preLoaderRoute: typeof AdminScorekeeperGameIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof AdminGamesRoute
    }
  }
}

interface AdminGamesRouteChildren {
  AdminGamesNewRoute: typeof AdminGamesNewRoute
}

const AdminGamesRouteChildren: AdminGamesRouteChildren = {
  AdminGamesNewRoute: AdminGamesNewRoute,
}

const AdminGamesRouteWithChildren = AdminGamesRoute._addFileChildren(
  AdminGamesRouteChildren,
)

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRouteWithChildren
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScorekeeperGameIdRoute: typeof AdminScorekeeperGameIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRouteWithChildren,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminScorekeeperGameIdRoute: AdminScorekeeperGameIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GamesGameIdRoute: GamesGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
