/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as ApiAutumnSplatRouteImport } from './routes/api.autumn.$'
import { Route as AdminTeamsNewRouteImport } from './routes/admin.teams.new'
import { Route as AdminTeamsImportRouteImport } from './routes/admin.teams.import'
import { Route as AdminScorekeeperGameIdRouteImport } from './routes/admin.scorekeeper.$gameId'
import { Route as AdminGamesNewRouteImport } from './routes/admin.games.new'
import { Route as AdminTeamsTeamIdEditRouteImport } from './routes/admin.teams.$teamId.edit'
import { Route as AdminGamesGameIdStreamRouteImport } from './routes/admin.games.$gameId.stream'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsNewRoute = AdminTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTeamsRoute,
} as any)
const AdminTeamsImportRoute = AdminTeamsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminTeamsRoute,
} as any)
const AdminScorekeeperGameIdRoute = AdminScorekeeperGameIdRouteImport.update({
  id: '/scorekeeper/$gameId',
  path: '/scorekeeper/$gameId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesNewRoute = AdminGamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminGamesRoute,
} as any)
const AdminTeamsTeamIdEditRoute = AdminTeamsTeamIdEditRouteImport.update({
  id: '/$teamId/edit',
  path: '/$teamId/edit',
  getParentRoute: () => AdminTeamsRoute,
} as any)
const AdminGamesGameIdStreamRoute = AdminGamesGameIdStreamRouteImport.update({
  id: '/$gameId/stream',
  path: '/$gameId/stream',
  getParentRoute: () => AdminGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/pricing': typeof PricingRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/games': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
  '/admin/teams/import': typeof AdminTeamsImportRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/admin/games/$gameId/stream': typeof AdminGamesGameIdStreamRoute
  '/admin/teams/$teamId/edit': typeof AdminTeamsTeamIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin': typeof AdminIndexRoute
  '/games': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
  '/admin/teams/import': typeof AdminTeamsImportRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/admin/games/$gameId/stream': typeof AdminGamesGameIdStreamRoute
  '/admin/teams/$teamId/edit': typeof AdminTeamsTeamIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/pricing': typeof PricingRoute
  '/admin/games': typeof AdminGamesRouteWithChildren
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/games/': typeof GamesIndexRoute
  '/admin/games/new': typeof AdminGamesNewRoute
  '/admin/scorekeeper/$gameId': typeof AdminScorekeeperGameIdRoute
  '/admin/teams/import': typeof AdminTeamsImportRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/admin/games/$gameId/stream': typeof AdminGamesGameIdStreamRoute
  '/admin/teams/$teamId/edit': typeof AdminTeamsTeamIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/pricing'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin/'
    | '/games'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
    | '/admin/teams/import'
    | '/admin/teams/new'
    | '/api/autumn/$'
    | '/admin/games/$gameId/stream'
    | '/admin/teams/$teamId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin'
    | '/games'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
    | '/admin/teams/import'
    | '/admin/teams/new'
    | '/api/autumn/$'
    | '/admin/games/$gameId/stream'
    | '/admin/teams/$teamId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/pricing'
    | '/admin/games'
    | '/admin/teams'
    | '/games/$gameId'
    | '/admin/'
    | '/games/'
    | '/admin/games/new'
    | '/admin/scorekeeper/$gameId'
    | '/admin/teams/import'
    | '/admin/teams/new'
    | '/api/autumn/$'
    | '/admin/games/$gameId/stream'
    | '/admin/teams/$teamId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PricingRoute: typeof PricingRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/new': {
      id: '/admin/teams/new'
      path: '/new'
      fullPath: '/admin/teams/new'
      preLoaderRoute: typeof AdminTeamsNewRouteImport
      parentRoute: typeof AdminTeamsRoute
    }
    '/admin/teams/import': {
      id: '/admin/teams/import'
      path: '/import'
      fullPath: '/admin/teams/import'
      preLoaderRoute: typeof AdminTeamsImportRouteImport
      parentRoute: typeof AdminTeamsRoute
    }
    '/admin/scorekeeper/$gameId': {
      id: '/admin/scorekeeper/$gameId'
      path: '/scorekeeper/$gameId'
      fullPath: '/admin/scorekeeper/$gameId'
      preLoaderRoute: typeof AdminScorekeeperGameIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games/new': {
      id: '/admin/games/new'
      path: '/new'
      fullPath: '/admin/games/new'
      preLoaderRoute: typeof AdminGamesNewRouteImport
      parentRoute: typeof AdminGamesRoute
    }
    '/admin/teams/$teamId/edit': {
      id: '/admin/teams/$teamId/edit'
      path: '/$teamId/edit'
      fullPath: '/admin/teams/$teamId/edit'
      preLoaderRoute: typeof AdminTeamsTeamIdEditRouteImport
      parentRoute: typeof AdminTeamsRoute
    }
    '/admin/games/$gameId/stream': {
      id: '/admin/games/$gameId/stream'
      path: '/$gameId/stream'
      fullPath: '/admin/games/$gameId/stream'
      preLoaderRoute: typeof AdminGamesGameIdStreamRouteImport
      parentRoute: typeof AdminGamesRoute
    }
  }
}

interface AdminGamesRouteChildren {
  AdminGamesNewRoute: typeof AdminGamesNewRoute
  AdminGamesGameIdStreamRoute: typeof AdminGamesGameIdStreamRoute
}

const AdminGamesRouteChildren: AdminGamesRouteChildren = {
  AdminGamesNewRoute: AdminGamesNewRoute,
  AdminGamesGameIdStreamRoute: AdminGamesGameIdStreamRoute,
}

const AdminGamesRouteWithChildren = AdminGamesRoute._addFileChildren(
  AdminGamesRouteChildren,
)

interface AdminTeamsRouteChildren {
  AdminTeamsImportRoute: typeof AdminTeamsImportRoute
  AdminTeamsNewRoute: typeof AdminTeamsNewRoute
  AdminTeamsTeamIdEditRoute: typeof AdminTeamsTeamIdEditRoute
}

const AdminTeamsRouteChildren: AdminTeamsRouteChildren = {
  AdminTeamsImportRoute: AdminTeamsImportRoute,
  AdminTeamsNewRoute: AdminTeamsNewRoute,
  AdminTeamsTeamIdEditRoute: AdminTeamsTeamIdEditRoute,
}

const AdminTeamsRouteWithChildren = AdminTeamsRoute._addFileChildren(
  AdminTeamsRouteChildren,
)

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRouteWithChildren
  AdminTeamsRoute: typeof AdminTeamsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScorekeeperGameIdRoute: typeof AdminScorekeeperGameIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRouteWithChildren,
  AdminTeamsRoute: AdminTeamsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminScorekeeperGameIdRoute: AdminScorekeeperGameIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PricingRoute: PricingRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
